# Generated by Django 3.2.13 on 2022-05-26 17:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20220520_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
