# Generated by Django 3.2.13 on 2022-05-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_postit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postit',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
