# Generated by Django 3.2.13 on 2022-05-29 21:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_postit_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
        migrations.AlterField(
            model_name='postit',
            name='heading',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='postit',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='palceholder', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
