# Generated by Django 3.2.13 on 2022-05-29 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20220529_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postit',
            name='votes',
        ),
    ]
